# One-off script used to seed data/events.json from the migration workbook.
# Kept for reference; edit data/events.json directly from now on.
import json, re
FIELDS = ["id","slug","date","startTime","endTime","title","subtitle","type","venueId","venueNote",
  "shortDescription","description","speaker","speakerBio","speakerUrl","image","imageAlt","price",
  "bookingUrl","bookingText","bookingNote","links","publicEvent","membersOnly","featured","cancelled","url","adminNotes"]
def ev(date, start, title, type_, slug, **kw):
    e = {k: "" for k in FIELDS}
    e.update(links=[], publicEvent=False, membersOnly=False, featured=False, cancelled=False)
    e.update(date=date, startTime=start, title=title, type=type_, slug=slug, id=f"ras-{date}-{slug}")
    e.update(kw)
    return {k: e[k] for k in FIELDS}
MEET_NOTE = "Monthly meetings are usually held at the Windmill Community Centre, Redditch."
E = [
 ev("2026-10-06","19:00","Discover the Night Sky","Public Event","discover-the-night-sky",
    endTime="21:00", subtitle="An evening of astronomy at Meadow Farm with AstroLee", venueId="meadow-farm",
    venueNote="Please note the change of venue: this event is at Meadow Farm, not our usual Windmill Community Centre.",
    shortDescription="A free evening of astronomy with AstroLee: an introduction to telescopes and astrophotography, followed by a free buffet.",
    description="Join Redditch Astronomical Society and AstroLee at Meadow Farm for a free evening of astronomy. A short indoor presentation will introduce telescopes and astrophotography, with tips on observing and photographing the night sky.\n\nThere will be a free buffet, and we will announce the winner of the Redditch Eclipse Photograph Competition and launch the society's 2027 fundraising raffle.\n\nThe evening runs for about two hours. Tickets are free but must be booked through Eventbrite.",
    speaker="AstroLee",
    speakerBio="AstroLee is an astrophotographer and astronomer from the West Midlands with a large following on Facebook.",
    price="Free", bookingUrl="https://www.eventbrite.com/e/discover-the-night-sky-an-evening-of-astronomy-at-the-meadow-farm-tickets-1996784755957",
    bookingText="Book a free ticket on Eventbrite",
    bookingNote="Tickets are free and booked through Eventbrite. On 29 September 2026 Eventbrite listed this event as sold out, so please check Eventbrite for availability.",
    publicEvent=True, featured=True,
    adminNotes="Title from Nic's build spec and the current Eventbrite listing ('Discover the Night Sky - An Evening of Astronomy at The Meadow Farm'). The old site link text called it 'Astrophotography with AstroLee'. Venue, times, free parking and programme from Eventbrite (checked 29 Sep 2026)."),
 ev("2026-11-03","19:00","Crime and Criminology of Space","Meeting","crime-and-criminology-of-space",
    endTime="21:00", venueNote=MEET_NOTE,
    shortDescription="A talk by Prof Jack Lampton on crime and criminology in space.",
    description="Our November meeting features a talk by Prof Jack Lampton on the crime and criminology of space. Further details will be added here when available.",
    speaker="Prof Jack Lampton",
    adminNotes="Workbook: current page provides title only. Venue not stated on old site; confirm (usually Windmill). End time assumed from the stated 7pm-9pm meeting pattern."),
 ev("2026-12-01","19:00","Christmas Meeting","Meeting","christmas-meeting",
    endTime="21:00", venueNote=MEET_NOTE,
    shortDescription="Our end-of-year Christmas meeting.",
    description="Our December meeting is the society's Christmas meeting. Details will be added here when they are confirmed.",
    adminNotes="From Nic's build spec (not in workbook or old site). Details and venue to confirm. The eclipse entry page says prizes will be presented 'by the December 3rd Society meeting' - 3 Dec 2026 is a Thursday; presumably this meeting."),
 ev("2026-09-01","19:00","Members' Evening","Meeting","members-evening",
    shortDescription="Society news and updates from members.",
    description="An evening of society news and member updates, including news of a talk at NAM 2026, the photo competition, the 2027 calendar and the AstroBerry software."),
 ev("2026-08-12","","Redditch Eclipse Photograph Competition","Public Event","eclipse-photograph-competition",
    url="/events/2026/eclipse-photograph-competition/", publicEvent=True,
    shortDescription="A free photo competition for pictures of the 12 August 2026 partial solar eclipse. Entries closed on 30 September 2026.",
    description="Our free competition for photographs of the partial solar eclipse on 12 August 2026.",
    adminNotes="Campaign page is hand-written at /events/2026/eclipse-photograph-competition/ (url override), so no page is generated for this record. Date is the eclipse date."),
 ev("2026-07-07","19:00","Where Art and Science Meet: Understanding the Universe Together","Meeting","where-art-and-science-meet",
    shortDescription="Ulrike Kuchner on where art and science meet in understanding the universe.",
    speaker="Ulrike Kuchner",
    speakerBio="Ulrike Kuchner is an astronomer, artist, curator and researcher of ArtScience, trained in both astrophysics (PhD) and fine arts (MFA). At the time of the talk Ulrike was a Senior Research Fellow in Astronomy at the University of Nottingham, co-leading ARTlab and co-coordinating the international SEADS collective of more than 200 practitioners."),
 ev("2026-06-02","19:00","The Big Bang Theory in Practice","Meeting","the-big-bang-theory-in-practice",
    shortDescription="A talk by Prof. Nial Tanvir.", speaker="Prof. Nial Tanvir"),
 ev("2026-05-16","09:00","National Space Centre Visit","Trip","national-space-centre-visit",
    venueId="national-space-centre", shortDescription="A society trip to the National Space Centre."),
 ev("2026-05-05","19:00","An Introduction to Radio Astronomy for Amateur Astronomers","Meeting","introduction-to-radio-astronomy",
    venueNote="Our guest speaker presented online.",
    shortDescription="Online guest Andrew Thornett on radio astronomy projects amateurs can try.",
    description="Andrew Thornett introduced the radio astronomy activities open to amateur astronomers, including listening to transmissions from the International Space Station, detecting meteors, picking up emissions from Jupiter, detecting solar flares and recording changes in the Earth's magnetic field.\n\nMost of these projects work whatever the weather and at any time of day.",
    speaker="Andrew Thornett"),
 ev("2026-04-07","19:00","The Dish","Meeting","the-dish"),
 ev("2026-03-03","19:00","NASA Dragonfly Mission","Meeting","nasa-dragonfly-mission"),
 ev("2026-02-03","19:00","Annual General Meeting","Meeting","agm",
    shortDescription="Election of the committee and a chance to shape the year ahead.",
    description="Our AGM, with the election of the committee and a chance for members to have their say on the society's activities for the year ahead.\n\nWeather permitting, the evening was to be followed by observing at Morton Stanley Park."),
 ev("2026-01-06","19:00","Telescope Workshop","Workshop","telescope-workshop",
    subtitle="What to do with that new Christmas telescope",
    shortDescription="Practical help with setting up and using a new telescope."),
 ev("2025-12-02","19:00","Annual Curry and Quiz Night","Social","curry-and-quiz-night",
    shortDescription="Our annual curry and quiz night, with food from Tilla Balti.",
    description="Our annual curry and quiz night, with food from Tilla Balti. Food orders were coordinated in advance through the committee.",
    links=[{"text":"Tilla Balti","url":"https://www.tillabaltiredditch.co.uk/"}]),
 ev("2025-11-04","19:00","Learning Astrophotography","Workshop","learning-astrophotography",
    venueId="windmill-centre",
    shortDescription="AstroLee on getting started in astrophotography, with a hands-on session if the weather allowed.",
    description="AstroLee talked about learning astrophotography, with hands-on experience at Morton Stanley Park if the weather allowed.",
    speaker="AstroLee",
    speakerBio="AstroLee is an astrophotographer and astronomer from the West Midlands. At the time of this talk AstroLee had over 300,000 followers on Facebook.",
    price="Members free, guests £3 (at the time)",
    adminNotes="Old site spells the speaker 'Astro Lee'; standardised to 'AstroLee' as used on Eventbrite. Guest price was the 2025 price, not a confirmed current fee."),
 ev("2025-10-07","19:00","The Monster in the Crab","Meeting","the-monster-in-the-crab",
    subtitle="OJ287, the largest binary black hole yet detected",
    shortDescription="Gary Poyner on OJ287, the largest binary black hole yet detected.",
    description="Gary Poyner's talk covered the discovery of OJ287, the professional-amateur observing campaigns running since the 1990s, results up to 2024 and the object's association with gravitational waves. The talk was a 60-minute presentation.",
    speaker="Gary Poyner"),
 ev("2023-05-02","19:00","Member Talk: Debunking Flat Earth Theory, and NASA Team Quiz","Meeting","flat-earth-and-nasa-quiz",
    shortDescription="A member talk debunking Flat Earth theory, followed by a NASA team quiz.",
    links=[{"text":"Physics World: Fighting flat-earth theory","url":"https://physicsworld.com/a/fighting-flat-earth-theory/"}]),
 ev("2023-04-04","19:00","Member Talks: ESA JUICE Mission and Flat Earth Theory","Meeting","juice-mission-and-flat-earth",
    shortDescription="Member talks on ESA's JUICE mission to Jupiter's icy moons and on debunking Flat Earth theory.",
    links=[{"text":"ESA: Juice mission","url":"https://www.esa.int/Science_Exploration/Space_Science/Juice"},
           {"text":"Physics World: Fighting flat-earth theory","url":"https://physicsworld.com/a/fighting-flat-earth-theory/"}]),
 ev("2023-03-07","19:00","A Very British Meteorite","Meeting","a-very-british-meteorite",
    venueId="online",
    shortDescription="Martin Lunn on the 1881 Middlesbrough meteorite.",
    description="Presented by Zoom, Martin Lunn told the story of the meteorite that fell near a railway line at Middlesbrough in 1881, described by the speaker as one of the most important on Earth.",
    speaker="Martin Lunn", speakerUrl="https://www.publicspeakerscorner.co.uk/martin-lunn-mbe-fras/"),
 ev("2023-02-18","16:30","Sidewalk Astronomy","Observing","sidewalk-astronomy",
    venueId="morton-stanley", publicEvent=True,
    shortDescription="Public observing at the Morton Stanley Park café.",
    description="Sidewalk astronomy at the Morton Stanley Park café. Visitors were encouraged to bring telescopes and warm clothes in case of clear skies."),
 ev("2023-02-07","19:00","Extraterrestrial Contact: How Would It Affect Us?","Meeting","extraterrestrial-contact",
    shortDescription="Martin Griffiths on how contact with extraterrestrial life might affect us.",
    speaker="Martin Griffiths", speakerUrl="https://martgrif.wixsite.com/astronomer",
    speakerBio="At the time of the talk, Martin Griffiths was Director of the Brecon Beacons Observatory and a Dark Sky Ambassador. Martin was also a founder member of the NASA Astrobiology Institute's Science Communication Group and a former programme manager for the European Science Foundation's astrobiology programme."),
 ev("2023-01-21","19:00","New Moon Observing","Observing","new-moon-observing",
    venueId="morton-stanley", shortDescription="Observing around new moon at Morton Stanley Park, weather permitting."),
 ev("2023-01-10","19:00","Open Evening: Winter Imaging and Observing","Meeting","open-evening-winter-imaging",
    shortDescription="An open evening discussing winter imaging options and observing."),
 ev("2022-12-13","19:00","Curry and Quiz Night","Social","curry-and-quiz-night",
    shortDescription="Our Christmas curry and quiz night (moved to the second Tuesday).",
    adminNotes="Old site marks this as a changed date."),
 ev("2022-12-04","19:30","Inter-society Quiz Night","Social","inter-society-quiz-night",
    shortDescription="An inter-society quiz hosted by Bromsgrove Astronomical Society, with Redditch defending their title.",
    description="An inter-society quiz night hosted by Bromsgrove Astronomical Society. Redditch went into the evening as the previous year's winners.",
    adminNotes="DATE TO CHECK: old site says 'Monday December 4th' but 4 Dec 2022 was a Sunday (5 Dec 2022 was a Monday). Workbook uses 2022-12-04."),
 ev("2022-11-01","19:00","Open Evening: The Sun and Astro-imaging","Meeting","open-evening-sun-and-astro-imaging",
    shortDescription="A member talk about the Sun and an astro-imaging workshop.",
    description="An open evening with a member talk from Ben about the Sun and an astro-imaging workshop led by Paul."),
 ev("2022-10-04","19:00","Open Evening: Telescopes","Meeting","open-evening-telescopes",
    shortDescription="Help with setting up telescopes, star party tips and plans for British Space Week.",
    description="An open evening covering telescope set-up and star party tips, with plans discussed for the Hive and British Space Week."),
 ev("2022-09-24","17:30","Star Party","Observing","star-party",
    venueId="morton-stanley", publicEvent=True,
    shortDescription="Sidewalk astronomy at the new café in Morton Stanley Park."),
 ev("2022-07-05","19:30","Building Galaxies One Star at a Time","Meeting","building-galaxies-one-star-at-a-time",
    shortDescription="Elizabeth Stanway on how we observe and interpret distant galaxies. Our first in-person speaker since March 2020.",
    description="Our first in-person speaker since March 2020. Elizabeth Stanway explained how astronomers observe and interpret galaxies, and how stellar population synthesis models are used to understand star formation and how galaxies have evolved from less than a billion years after the Big Bang onwards.\n\nMembers and non-members alike were welcome.",
    speaker="Elizabeth Stanway",
    speakerBio="At the time of the talk, Elizabeth Stanway was a Reader in Astronomy and Astrophysics at the University of Warwick, where Elizabeth had lectured since 2011. Earlier posts included the University of Bristol and the University of Wisconsin-Madison, and Elizabeth gained a PhD at the Institute of Astronomy, Cambridge. Elizabeth's research focuses on using stellar population synthesis to interpret star-forming populations across cosmic time, with further interests in astrophysical transients and the dialogue between science and science fiction."),
]
# Past events inherit the standard end time only when upcoming; leave blank otherwise.
E.sort(key=lambda e: (e["date"], e["startTime"]))
ids = [e["id"] for e in E]; assert len(ids) == len(set(ids)), "duplicate ids"
json.dump(E, open("data/events.json","w"), indent=2, ensure_ascii=False)
open("data/events.json","a").write("\n")
print(len(E), "events")
